language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install ;
- v8_install ;
- dcmtk_install ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; echo "reset R"
  ; alias R="travis_wait 100 ${x}" ; fi
- install_python_requirements ;
- R CMD javareconf ;
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: vZMzA9IOmd9XJ0SQUE2biaW+VPA+jjDT+e4av9rye7HFu8jP7cTJ1GpWhKGSLMR+5kJC8fQe7mtgJylvAvGYwhLRpvG+PMZz3cD9HPe+fJ6KCM7HhPP5T/cs8VPcApsVqkcYXNjrvkMwVgZLRwK5sPFs5CxSx/drjF1oX2L101QPG77PSyEEfOrlEoQnVLN0tvOIMtfnIavN9K0C7dwLSVuWCbm+tmQxb/EtgfkdNozVNPNSkvQdLYciU2dlPqA7Nf9B/bbhyUAz3X/Uz8xoW/h8TOvcE0qoBPlEjvNydczPYWYUhMA0BEkG3W3I9bZ3rsv62k+NxnlptVeGhlMDm7iQDfPruGoCP7sq1RlWhC01jNs0dvfOCru8fjIkEkTZYILcxI9+cAmSEeaz/YMMk19wzw7yKIxgVL/k0CHkqqX77zMcCwxt2Wf0M8gN5gJMYdond6wzIJmUv7RUMHIWvFRQolLpzhWSzSN7QyYQOQvIGSGyBrqt3KPNPA+2WAU7+TNU9+Hi3V5IW+dyN67bSDrntfr7+H9pKMHyH+lceQyLgwDOFuLN+Ycjlvd26BBBpe7CxP+c+A0MS6S550Y9zmV0atcvrf/2imlrGF1Js18ULxgDAGhSzzJhudeYv7tzMj0qt3k+rJlIlC0zriVbOr4Z8sRqMxUMWRmdwYlOGTw=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all", quiet = FALSE)' > neuroc_covr.R ; travis_wait
  100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
